db:
  image: mysql:5.7
  volumes:
    - "./db:/docker-entrypoint-initdb.d"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: "chris-video-streaming"
  ports:
    - "3306:3306"
web:
  build: .
  command: video-service
  volumes:
    - "./www:/var/www/html"
  links:
    - db
  ports:
    - "80:80"
  restart: always

