db:
  image: mysql:5.7
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  ports:
    - "3306:3306"
apache:
  build: .
  volumes:
      - .:/var/www/html
  links:
      - db
  ports:
      - "80:80"
